//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://epam.com/learn/parody_CD")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://epam.com/learn/parody_CD", IsNullable=false)]
public partial class CD {
    
    private string artistField;
    
    private string titleField;
    
    private string genreField;
    
    private ushort datereleasedField;
    
    private CDSong[] songField;
    
    private string serialField;
    
    private string disclengthField;
    
    /// <remarks/>
    public string artist {
        get {
            return this.artistField;
        }
        set {
            this.artistField = value;
        }
    }
    
    /// <remarks/>
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public string genre {
        get {
            return this.genreField;
        }
        set {
            this.genreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("date-released")]
    public ushort datereleased {
        get {
            return this.datereleasedField;
        }
        set {
            this.datereleasedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("song")]
    public CDSong[] song {
        get {
            return this.songField;
        }
        set {
            this.songField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string serial {
        get {
            return this.serialField;
        }
        set {
            this.serialField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("disc-length")]
    public string disclength {
        get {
            return this.disclengthField;
        }
        set {
            this.disclengthField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://epam.com/learn/parody_CD")]
public partial class CDSong {
    
    private string titleField;
    
    private CDSongLength lengthField;
    
    private CDSongParody parodyField;
    
    /// <remarks/>
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public CDSongLength length {
        get {
            return this.lengthField;
        }
        set {
            this.lengthField = value;
        }
    }
    
    /// <remarks/>
    public CDSongParody parody {
        get {
            return this.parodyField;
        }
        set {
            this.parodyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://epam.com/learn/parody_CD")]
public partial class CDSongLength {
    
    private byte minutesField;
    
    private byte secondsField;
    
    /// <remarks/>
    public byte minutes {
        get {
            return this.minutesField;
        }
        set {
            this.minutesField = value;
        }
    }
    
    /// <remarks/>
    public byte seconds {
        get {
            return this.secondsField;
        }
        set {
            this.secondsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://epam.com/learn/parody_CD")]
public partial class CDSongParody {
    
    private string titleField;
    
    private string artistField;
    
    /// <remarks/>
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public string artist {
        get {
            return this.artistField;
        }
        set {
            this.artistField = value;
        }
    }
}
